#!/bin/bash
PSScriptRoot=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) #removeline
cd /media/c/gdrive/Documentos #removeline
uv run --project "$PSScriptRoot" "$PSScriptRoot/main.py" "$@"